const data = [
  {
    id: "eo7g4wunxxxr8uv45q8p5x638",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774976400,
    comp: {
      id: "581t4mywybx21wcpmpykhyzr3",
      name: "Liga Profesional Argentina",
      nameSeo: "liga-profesional-argentina",
      country: {
        id: "2vovxa97k7v7ofa85dah2xktb",
        name: "argentina",
        fullName: "Argentina",
        nameSeo: "argentina",
        flag: "/images/flags/ar.svg",
      },
      link: "/en_GB/soccer/liga-profesional-argentina-2026/8v84l9nq3d5t0j4gb781i3llg/results",
    },
    link: "/en_GB/soccer/liga-profesional-argentina-2026/8v84l9nq3d5t0j4gb781i3llg/match/aldosivi-vs-argentinos-juniors/eo7g4wunxxxr8uv45q8p5x638",
    home: {
      id: "daclh04s6dduu6f9yw7fm8w6r",
      name: "Aldosivi",
    },
    away: {
      id: "7tev5pifn8hdy4vlts0coha1b",
      name: "Argentinos Juniors",
    },
    updated: 1774543041,
  },
  {
    id: "6gc5eunx69dg6ztak55cld34k",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774992600,
    comp: {
      id: "5zr0b05eyx25km7z1k03ca9jx",
      name: "Serie B",
      nameSeo: "serie-b",
      country: {
        id: "2vufyvpoxd9lfl9f6vpp7tz6y",
        name: "brazil",
        fullName: "Brazil",
        nameSeo: "brazil",
        flag: "/images/flags/br.svg",
      },
      link: "/en_GB/soccer/serie-b-2026/7pt8trpd4rbju1v568nuskdn8/results",
    },
    link: "/en_GB/soccer/serie-b-2026/7pt8trpd4rbju1v568nuskdn8/match/juventude-vs-novorizontino/6gc5eunx69dg6ztak55cld34k",
    home: {
      id: "7avb9meepw828qkp0tiugzd1b",
      name: "Juventude",
    },
    away: {
      id: "9cl05467nuteeh2yk1ylr897l",
      name: "Novorizontino",
    },
    updated: 1774871925,
  },
  {
    id: "6dygds8xq38dzg9t45o2nvaj8",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774994400,
    comp: {
      id: "5zr0b05eyx25km7z1k03ca9jx",
      name: "Serie B",
      nameSeo: "serie-b",
      country: {
        id: "2vufyvpoxd9lfl9f6vpp7tz6y",
        name: "brazil",
        fullName: "Brazil",
        nameSeo: "brazil",
        flag: "/images/flags/br.svg",
      },
      link: "/en_GB/soccer/serie-b-2026/7pt8trpd4rbju1v568nuskdn8/results",
    },
    link: "/en_GB/soccer/serie-b-2026/7pt8trpd4rbju1v568nuskdn8/match/fortaleza-vs-cuiabá/6dygds8xq38dzg9t45o2nvaj8",
    home: {
      id: "1vvaya787s5wg5geudzacya7m",
      name: "Fortaleza",
    },
    away: {
      id: "3oau1zwakraexd8ej8xvtlaqo",
      name: "Cuiabá",
    },
    updated: 1774871924,
  },
  {
    id: "8jgm2kc9sn2czpq5cj7xw8vmc",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774982700,
    comp: {
      id: "39q1hq42hxjfylxb7xpe9bvf9",
      name: "UEFA World Cup Qualifiers",
      nameSeo: "uefa-world-cup-qualifiers",
      country: {
        id: "7yiwjcnhat6jo3f901h266cwl",
        name: "europe",
        fullName: "Europe",
        nameSeo: "europe",
        flag: "/images/flags/uefa.png",
      },
      link: "/en_GB/soccer/uefa-world-cup-qualifiers-2026-canada-mexico-united-states/cscd2arb9anef4wya15c3djbo/results",
    },
    link: "/en_GB/soccer/uefa-world-cup-qualifiers-2026-canada-mexico-united-states/cscd2arb9anef4wya15c3djbo/match/bosnia-herzegovina-vs-italy/8jgm2kc9sn2czpq5cj7xw8vmc",
    home: {
      id: "o5iztj2zl6b0v6ed9q5m7p1k",
      name: "Bosnia-Herzegovina",
    },
    away: {
      id: "eks08q2vbr45w563zrctsl5xo",
      name: "Italy",
    },
    updated: 1774944376,
  },
  {
    id: "ewvi3ozgo7prpj4oz4xlojw9g",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774982700,
    comp: {
      id: "39q1hq42hxjfylxb7xpe9bvf9",
      name: "UEFA World Cup Qualifiers",
      nameSeo: "uefa-world-cup-qualifiers",
      country: {
        id: "7yiwjcnhat6jo3f901h266cwl",
        name: "europe",
        fullName: "Europe",
        nameSeo: "europe",
        flag: "/images/flags/uefa.png",
      },
      link: "/en_GB/soccer/uefa-world-cup-qualifiers-2026-canada-mexico-united-states/cscd2arb9anef4wya15c3djbo/results",
    },
    link: "/en_GB/soccer/uefa-world-cup-qualifiers-2026-canada-mexico-united-states/cscd2arb9anef4wya15c3djbo/match/czechia-vs-denmark/ewvi3ozgo7prpj4oz4xlojw9g",
    home: {
      id: "70tnqyqn871jwlk26gtjw7knm",
      name: "Czechia",
    },
    away: {
      id: "akblgvrthxxgta4ou9lnslxgb",
      name: "Denmark",
    },
    updated: 1774944377,
  },
  {
    id: "azfmibj0cf4o1wb5khmr5hul0",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774982700,
    comp: {
      id: "39q1hq42hxjfylxb7xpe9bvf9",
      name: "UEFA World Cup Qualifiers",
      nameSeo: "uefa-world-cup-qualifiers",
      country: {
        id: "7yiwjcnhat6jo3f901h266cwl",
        name: "europe",
        fullName: "Europe",
        nameSeo: "europe",
        flag: "/images/flags/uefa.png",
      },
      link: "/en_GB/soccer/uefa-world-cup-qualifiers-2026-canada-mexico-united-states/cscd2arb9anef4wya15c3djbo/results",
    },
    link: "/en_GB/soccer/uefa-world-cup-qualifiers-2026-canada-mexico-united-states/cscd2arb9anef4wya15c3djbo/match/kosovo-vs-türkiye/azfmibj0cf4o1wb5khmr5hul0",
    home: {
      id: "7k420bggr3y9w1xnkf2kkqiah",
      name: "Kosovo",
    },
    away: {
      id: "9s2kpeunkes0g17l95r3t91j6",
      name: "Türkiye",
    },
    updated: 1774944377,
  },
  {
    id: "9r3tkw7ng8w4d2ydsxfyfllas",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774982700,
    comp: {
      id: "39q1hq42hxjfylxb7xpe9bvf9",
      name: "UEFA World Cup Qualifiers",
      nameSeo: "uefa-world-cup-qualifiers",
      country: {
        id: "7yiwjcnhat6jo3f901h266cwl",
        name: "europe",
        fullName: "Europe",
        nameSeo: "europe",
        flag: "/images/flags/uefa.png",
      },
      link: "/en_GB/soccer/uefa-world-cup-qualifiers-2026-canada-mexico-united-states/cscd2arb9anef4wya15c3djbo/results",
    },
    link: "/en_GB/soccer/uefa-world-cup-qualifiers-2026-canada-mexico-united-states/cscd2arb9anef4wya15c3djbo/match/sweden-vs-poland/9r3tkw7ng8w4d2ydsxfyfllas",
    home: {
      id: "4w1ktgu1nbbgqfe3ssbb4fg5v",
      name: "Sweden",
    },
    away: {
      id: "ba25ib8pofxr85hkbs8lt7kw7",
      name: "Poland",
    },
    updated: 1774944377,
  },
  {
    id: "4njowfacomzdb9av82px9436c",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774972800,
    comp: {
      id: "595nsvo7ykvoe690b1e4u5n56",
      name: "UEFA Nations League",
      nameSeo: "uefa-nations-league",
      country: {
        id: "7yiwjcnhat6jo3f901h266cwl",
        name: "europe",
        fullName: "Europe",
        nameSeo: "europe",
        flag: "/images/flags/uefa.png",
      },
      link: "/en_GB/soccer/uefa-nations-league-2024-2025/3r70u3fqh4hthsa2j4hsefis/results",
    },
    link: "/en_GB/soccer/uefa-nations-league-2024-2025/3r70u3fqh4hthsa2j4hsefis/match/latvia-vs-gibraltar/4njowfacomzdb9av82px9436c",
    home: {
      id: "cyngwp50jfiewrgyzhlaw1z9e",
      name: "Latvia",
    },
    away: {
      id: "8erx2n6k576zhzoz2zjqd4v4o",
      name: "Gibraltar",
    },
    score: {
      aggregate: {
        home: 1,
        away: 0,
      },
    },
    updated: 1774944378,
  },
  {
    id: "4nyohb74pj3kbxnj7otsjqsk4",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774972800,
    comp: {
      id: "595nsvo7ykvoe690b1e4u5n56",
      name: "UEFA Nations League",
      nameSeo: "uefa-nations-league",
      country: {
        id: "7yiwjcnhat6jo3f901h266cwl",
        name: "europe",
        fullName: "Europe",
        nameSeo: "europe",
        flag: "/images/flags/uefa.png",
      },
      link: "/en_GB/soccer/uefa-nations-league-2024-2025/3r70u3fqh4hthsa2j4hsefis/results",
    },
    link: "/en_GB/soccer/uefa-nations-league-2024-2025/3r70u3fqh4hthsa2j4hsefis/match/luxembourg-vs-malta/4nyohb74pj3kbxnj7otsjqsk4",
    home: {
      id: "2yvmq0cz7jjwh4x15yj8lzad4",
      name: "Luxembourg",
    },
    away: {
      id: "78vzyth2iuzt3fpaqrfunkr0j",
      name: "Malta",
    },
    score: {
      aggregate: {
        home: 2,
        away: 0,
      },
    },
    updated: 1774944379,
  },
  {
    id: "7i5sfh41cjpwg4l972dm487x0",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774976400,
    comp: {
      id: "3is4bkgf3loxv9qfg3hm8zfqb",
      name: "Segunda División",
      nameSeo: "segunda-división",
      country: {
        id: "49ih1pwv3ahshdf8uzrimi54c",
        name: "spain",
        fullName: "Spain",
        nameSeo: "spain",
        flag: "/images/flags/es.svg",
      },
      link: "/en_GB/soccer/segunda-división-2025-2026/dko0hzifl1xv9c51s3ai017v8/results",
    },
    link: "/en_GB/soccer/segunda-división-2025-2026/dko0hzifl1xv9c51s3ai017v8/match/mirandés-vs-albacete/7i5sfh41cjpwg4l972dm487x0",
    home: {
      id: "a745ojopc6f75ma1fyfzayono",
      name: "Mirandés",
    },
    away: {
      id: "13zq8jfp5uydowd3ibknxaffj",
      name: "Albacete",
    },
    updated: 1774869307,
  },
  {
    id: "7ixaiiptli5ek32kuybuni4gk",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774980000,
    comp: {
      id: "3is4bkgf3loxv9qfg3hm8zfqb",
      name: "Segunda División",
      nameSeo: "segunda-división",
      country: {
        id: "49ih1pwv3ahshdf8uzrimi54c",
        name: "spain",
        fullName: "Spain",
        nameSeo: "spain",
        flag: "/images/flags/es.svg",
      },
      link: "/en_GB/soccer/segunda-división-2025-2026/dko0hzifl1xv9c51s3ai017v8/results",
    },
    link: "/en_GB/soccer/segunda-división-2025-2026/dko0hzifl1xv9c51s3ai017v8/match/deportivo-de-la-coruña-vs-córdoba/7ixaiiptli5ek32kuybuni4gk",
    home: {
      id: "1r541mega6d838hi0p44sv0h2",
      name: "Deportivo de La Coruña",
    },
    away: {
      id: "7tpg5hj5gutjb58m6trjcaika",
      name: "Córdoba",
    },
    updated: 1774869305,
  },
  {
    id: "7ijhsloieg4t9yp5cxp0duln8",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774985400,
    comp: {
      id: "3is4bkgf3loxv9qfg3hm8zfqb",
      name: "Segunda División",
      nameSeo: "segunda-división",
      country: {
        id: "49ih1pwv3ahshdf8uzrimi54c",
        name: "spain",
        fullName: "Spain",
        nameSeo: "spain",
        flag: "/images/flags/es.svg",
      },
      link: "/en_GB/soccer/segunda-división-2025-2026/dko0hzifl1xv9c51s3ai017v8/results",
    },
    link: "/en_GB/soccer/segunda-división-2025-2026/dko0hzifl1xv9c51s3ai017v8/match/real-valladolid-vs-cádiz/7ijhsloieg4t9yp5cxp0duln8",
    home: {
      id: "4jelr92fsge73q39is6qvhxb3",
      name: "Real Valladolid",
    },
    away: {
      id: "82q9159y2u7mkfn3z6hy75r4o",
      name: "Cádiz",
    },
    updated: 1774869307,
  },
  {
    id: "emk296tsf6rue61zqhr7mstg4",
    status: "played",
    coverage: 13,
    period: 14,
    date: 1774936800,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/cameroon-vs-china-pr/emk296tsf6rue61zqhr7mstg4",
    home: {
      id: "b6ojzaz5yyr6dkrj284hrhhs1",
      name: "Cameroon",
    },
    away: {
      id: "bur06vhektmgozn47md9dptk3",
      name: "China PR",
    },
    score: {
      ht: {
        home: 2,
        away: 0,
      },
      ft: {
        home: 2,
        away: 0,
      },
      total: {
        home: 2,
        away: 0,
      },
    },
    events: [
      {
        periodId: 1,
        min: 3,
        timeStr: "2:17",
        teamId: "b6ojzaz5yyr6dkrj284hrhhs1",
        entity_type: "goal",
        playerId: "bl3o0pt262qax5cwv4jeu82s4",
        playerName: "K. Etta Eyong",
        type: "G",
        player2Id: "7y2h0upi10c3mp7u2oqn9kq38",
        player2Name: "A. Nagida",
        score: [1, 0],
      },
      {
        periodId: 1,
        min: 9,
        timeStr: "8:28",
        teamId: "b6ojzaz5yyr6dkrj284hrhhs1",
        entity_type: "goal",
        playerId: "467ykpwj32c3eip2ga0yts60a",
        playerName: "S. Alioum",
        type: "G",
        player2Id: "95ykmewcxabpd1kgg60znel90",
        player2Name: "K. Nifanso",
        score: [2, 0],
      },
      {
        periodId: 2,
        min: 46,
        timeStr: "45:00",
        teamId: "bur06vhektmgozn47md9dptk3",
        entity_type: "sub",
        playerId: "5ke7oy9eu1wcbyrkuy3xwykx6",
        playerName: "Huang Jiahui",
        player2Id: "d7z66ss3lc6fcoa44p3t8f2fo",
        player2Name: "Umidjan Yusup",
      },
      {
        periodId: 2,
        min: 46,
        timeStr: "45:00",
        teamId: "bur06vhektmgozn47md9dptk3",
        entity_type: "sub",
        playerId: "eh4r1jaa7fngfcmeq6vk2cqcq",
        playerName: "Li Yang",
        player2Id: "3a5g1p06q1up0tzc7rfoyoc9g",
        player2Name: "Hu Hetao",
      },
      {
        periodId: 2,
        min: 46,
        timeStr: "45:00",
        teamId: "bur06vhektmgozn47md9dptk3",
        entity_type: "sub",
        playerId: "3rkjhd2p3ii2b0046mp6adgd0",
        playerName: "Behram Abduweli",
        player2Id: "bhdxueb52i8jdfz3dpsqz48vd",
        player2Name: "Zhang Yuning",
      },
      {
        periodId: 2,
        min: 46,
        timeStr: "45:00",
        teamId: "bur06vhektmgozn47md9dptk3",
        entity_type: "sub",
        playerId: "7ebj2h6w9nij1lx90lraosg6h",
        playerName: "Lin Liangming",
        player2Id: "eyagaoi7782r6afrdvoooqxn9",
        player2Name: "Wang Shangyuan",
      },
      {
        periodId: 2,
        min: 48,
        timeStr: "47:31",
        teamId: "b6ojzaz5yyr6dkrj284hrhhs1",
        entity_type: "card",
        playerId: "39bcswfqnpa07b4afevezejo4",
        playerName: "J. Tchatchoua",
        type: "YC",
        reason: "Foul",
      },
      {
        periodId: 2,
        min: 58,
        timeStr: "57:10",
        teamId: "b6ojzaz5yyr6dkrj284hrhhs1",
        entity_type: "card",
        playerId: "e32urdrdkp44zmnt6ptg0k12i",
        playerName: "D. Yongwa",
        type: "YC",
        reason: "Dissent",
      },
      {
        periodId: 2,
        min: 58,
        timeStr: "57:15",
        teamId: "b6ojzaz5yyr6dkrj284hrhhs1",
        entity_type: "card",
        type: "RC",
        reason: "Foul and Abusive Language",
      },
      {
        periodId: 2,
        min: 65,
        timeStr: "64:43",
        teamId: "b6ojzaz5yyr6dkrj284hrhhs1",
        entity_type: "sub",
        playerId: "f3zl8ymo5ttze20sffzk044q1",
        playerName: "D. Namaso",
        player2Id: "aqv8eg1t8pipkyziug9d23or8",
        player2Name: "M. Fernandez",
      },
      {
        periodId: 2,
        min: 66,
        timeStr: "65:15",
        teamId: "b6ojzaz5yyr6dkrj284hrhhs1",
        entity_type: "sub",
        playerId: "bxdqxy4grh0ct3d8emys8qxw4",
        playerName: "O. Kamdem",
        player2Id: "95ykmewcxabpd1kgg60znel90",
        player2Name: "K. Nifanso",
      },
      {
        periodId: 2,
        min: 70,
        timeStr: "69:08",
        teamId: "b6ojzaz5yyr6dkrj284hrhhs1",
        entity_type: "card",
        playerId: "12198ym7w99a8ckjrr6p734t0",
        playerName: "S. Keller",
        type: "YC",
        reason: "Foul",
      },
      {
        periodId: 2,
        min: 70,
        timeStr: "69:47",
        teamId: "b6ojzaz5yyr6dkrj284hrhhs1",
        entity_type: "sub",
        playerId: "5wsz3usdkj01snq28pzpiwb2s",
        playerName: "A. Avom",
        player2Id: "egz137gakqc4xcxvfacqjb4es",
        player2Name: "A. Kamdem",
      },
      {
        periodId: 2,
        min: 70,
        timeStr: "69:49",
        teamId: "b6ojzaz5yyr6dkrj284hrhhs1",
        entity_type: "sub",
        playerId: "44m4s9f1ckgdavmqjo0icx016",
        playerName: "R. Fosso",
        player2Id: "50ko0lrtx1vu0d1lnb9a0xses",
        player2Name: "A. Yondjio",
      },
      {
        periodId: 2,
        min: 75,
        timeStr: "74:50",
        teamId: "bur06vhektmgozn47md9dptk3",
        entity_type: "sub",
        playerId: "b9cgj62n2tyygcl0aiiffbdw4",
        playerName: "Xie Wenneng",
        player2Id: "dx5z3vr1btogw99sbcs4cb47o",
        player2Name: "Wang Yudong",
      },
      {
        periodId: 2,
        min: 79,
        timeStr: "78:25",
        teamId: "bur06vhektmgozn47md9dptk3",
        entity_type: "card",
        playerId: "b9cgj62n2tyygcl0aiiffbdw4",
        playerName: "Xie Wenneng",
        type: "YC",
        reason: "Foul",
      },
      {
        periodId: 2,
        min: 80,
        timeStr: "79:35",
        teamId: "bur06vhektmgozn47md9dptk3",
        entity_type: "sub",
        playerId: "267luqy1xlftzu24lh6433obt",
        playerName: "Gao Tianyi",
        player2Id: "c6xha7fg2kd5mc6ah82cfhrkl",
        player2Name: "Wei Shihao",
      },
      {
        periodId: 2,
        min: 87,
        timeStr: "86:14",
        teamId: "bur06vhektmgozn47md9dptk3",
        entity_type: "sub",
        playerId: "641iave0xdptrp5jesrmrxwb9",
        playerName: "Ba Dun",
        player2Id: "71qos3l44yp9lgh2dgcteym1g",
        player2Name: "Yang Xi",
      },
      {
        periodId: 2,
        min: 87,
        timeStr: "86:47",
        teamId: "b6ojzaz5yyr6dkrj284hrhhs1",
        entity_type: "sub",
        playerId: "7amefftr5evwcnzm718rfh9n8",
        playerName: "C. Kofane",
        player2Id: "bl3o0pt262qax5cwv4jeu82s4",
        player2Name: "K. Etta Eyong",
      },
      {
        periodId: 2,
        min: 91,
        timeStr: "90:57",
        teamId: "b6ojzaz5yyr6dkrj284hrhhs1",
        entity_type: "card",
        playerId: "12198ym7w99a8ckjrr6p734t0",
        playerName: "S. Keller",
        type: "Y2C",
        reason: "Foul",
      },
      {
        periodId: 2,
        min: 92,
        timeStr: "91:27",
        teamId: "bur06vhektmgozn47md9dptk3",
        entity_type: "card",
        playerId: "3rkjhd2p3ii2b0046mp6adgd0",
        playerName: "Behram Abduweli",
        type: "YC",
        reason: "Argument",
      },
    ],
    updated: 1774943570,
  },
  {
    id: "e86jxa4h6bwza0r9w1lb2fbis",
    status: "fixture",
    coverage: 1,
    period: 16,
    date: 1774947600,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/equatorial-guinea-vs-madagascar/e86jxa4h6bwza0r9w1lb2fbis",
    home: {
      id: "9ctt1n42zkszkabxdhzixsidc",
      name: "Equatorial Guinea",
    },
    away: {
      id: "9kkn65uke5h6mx936kajcqw5k",
      name: "Madagascar",
    },
    updated: 1774780220,
  },
  {
    id: "emwi8lmgce7goyftoxx4m036c",
    status: "playing",
    coverage: 13,
    period: 2,
    date: 1774948200,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/australia-vs-curaçao/emwi8lmgce7goyftoxx4m036c",
    time: 46,
    home: {
      id: "bl4fd8cxe6kjvjx8br82gkhnq",
      name: "Australia",
    },
    away: {
      id: "3csexoalt9hfesmo2p4619ga4",
      name: "Curaçao",
    },
    score: {
      ht: {
        home: 1,
        away: 0,
      },
      ft: {
        home: 1,
        away: 0,
      },
      total: {
        home: 1,
        away: 0,
      },
    },
    events: [
      {
        periodId: 1,
        min: 23,
        timeStr: "22:44",
        teamId: "bl4fd8cxe6kjvjx8br82gkhnq",
        entity_type: "goal",
        playerId: "9rm0qaumcii8d9zqxkh9nq4lx",
        playerName: "A. Mabil",
        type: "G",
        score: [1, 0],
      },
      {
        periodId: 2,
        min: 46,
        timeStr: "45:00",
        teamId: "bl4fd8cxe6kjvjx8br82gkhnq",
        entity_type: "sub",
        playerId: "5hylntpne6d7xwey2v9d9lg8a",
        playerName: "N. Velupillay",
        player2Id: "2zwe056wfzof0v5jv01dv9uc5",
        player2Name: "A. Hrustić",
      },
      {
        periodId: 2,
        min: 46,
        timeStr: "45:00",
        teamId: "bl4fd8cxe6kjvjx8br82gkhnq",
        entity_type: "sub",
        playerId: "95sml1vx1fwwhq8p32p60e11x",
        playerName: "J. Geria",
        player2Id: "mmfx7i96rntv049enlwym8es",
        player2Name: "L. Herrington",
      },
      {
        periodId: 2,
        min: 46,
        timeStr: "45:00",
        teamId: "bl4fd8cxe6kjvjx8br82gkhnq",
        entity_type: "sub",
        playerId: "deqaqharcni59p762zcfum6tw",
        playerName: "P. Okon",
        player2Id: "1igjz2w9dr9mj5f4ade5plsve",
        player2Name: "C. Metcalfe",
      },
      {
        periodId: 2,
        min: 46,
        timeStr: "45:00",
        teamId: "3csexoalt9hfesmo2p4619ga4",
        entity_type: "sub",
        playerId: "baghnvel8qsn5k9s79jiyldnu",
        playerName: "A. Martha",
        player2Id: "apzgvyoya5b4yd6vpev9o7krt",
        player2Name: "T. Chong",
      },
      {
        periodId: 2,
        min: 46,
        timeStr: "45:00",
        teamId: "3csexoalt9hfesmo2p4619ga4",
        entity_type: "sub",
        playerId: "en1pg53s5zagsx7wg6tossnah",
        playerName: "G. Roemeratoe",
        player2Id: "d9ewnngnsfc0s4hcs282hayhg",
        player2Name: "L. Comenencia",
      },
      {
        periodId: 2,
        min: 46,
        timeStr: "45:00",
        teamId: "3csexoalt9hfesmo2p4619ga4",
        entity_type: "sub",
        playerId: "3a89nlkh1p3l3qi6o70uzp5ud",
        playerName: "G. Kastaneer",
        player2Id: "ix6hcbfujuw3mgefzpsnp2zu",
        player2Name: "J. Antonisse",
      },
      {
        periodId: 2,
        min: 46,
        timeStr: "45:00",
        teamId: "3csexoalt9hfesmo2p4619ga4",
        entity_type: "sub",
        playerId: "6dpxvfpnaua6y4gevop02qc8a",
        playerName: "J. Margaritha",
        player2Id: "7053nqhl9wu2u1kegzo9aopg5",
        player2Name: "B. Kuwas",
      },
    ],
    updated: 1774952190,
  },
  {
    id: "8gmzwag7jar578fh3qbelr9jo",
    status: "fixture",
    coverage: 7,
    period: 16,
    date: 1774958400,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/kazakhstan-vs-comoros/8gmzwag7jar578fh3qbelr9jo",
    home: {
      id: "bjfbr79r75nhf4oz80jxarv8f",
      name: "Kazakhstan",
    },
    away: {
      id: "i9syypvx4y58uy9r2oxzuisd",
      name: "Comoros",
    },
    updated: 1774699280,
  },
  {
    id: "2m3el0vo1u9gk71mquxcuq7f8",
    status: "fixture",
    coverage: 1,
    period: 16,
    date: 1774962000,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/botswana-vs-malawi/2m3el0vo1u9gk71mquxcuq7f8",
    home: {
      id: "7wkvdl4pc28z7pjutt7g20fy1",
      name: "Botswana",
    },
    away: {
      id: "biwpsv8gxe690rlvcgs8wlo9v",
      name: "Malawi",
    },
    updated: 1774854920,
  },
  {
    id: "cxjzlvdxv29yxkk0fgoppesr8",
    status: "fixture",
    coverage: 9,
    period: 16,
    date: 1774962000,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/ir-iran-vs-costa-rica/cxjzlvdxv29yxkk0fgoppesr8",
    home: {
      id: "cubclbw5k5gdqdau95bnav0nn",
      name: "IR Iran",
    },
    away: {
      id: "bfgqfm4qa3mal7fll74wd04mu",
      name: "Costa Rica",
    },
    updated: 1774631252,
  },
  {
    id: "dftejbvd22sp7rzjo84cq7pck",
    status: "fixture",
    coverage: 1,
    period: 16,
    date: 1774969200,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/liberia-vs-libya/dftejbvd22sp7rzjo84cq7pck",
    home: {
      id: "6fcfpek2a9xlkutt3k2ey0a9w",
      name: "Liberia",
    },
    away: {
      id: "4o7g2gcppu8rlle3gtdolsnay",
      name: "Libya",
    },
    updated: 1774373772,
  },
  {
    id: "ccpi6fr5ncufqqrcmd4tcjvh0",
    status: "fixture",
    coverage: 9,
    period: 16,
    date: 1774972800,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/montenegro-vs-slovenia/ccpi6fr5ncufqqrcmd4tcjvh0",
    home: {
      id: "6agojcuvg4c9fkcm2gpfiiahd",
      name: "Montenegro",
    },
    away: {
      id: "vle4kgkwxllbxecwqxcmtiwn",
      name: "Slovenia",
    },
    updated: 1774818178,
  },
  {
    id: "5q46yotr4lplgjphwtii1y1p0",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774972800,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/norway-vs-switzerland/5q46yotr4lplgjphwtii1y1p0",
    home: {
      id: "e1vf7kzswllumuykwezkrbo70",
      name: "Norway",
    },
    away: {
      id: "339wxbt07ltnva7hop6m5o477",
      name: "Switzerland",
    },
    updated: 1774277655,
  },
  {
    id: "327w577byq8okh8gsns0fb0gk",
    status: "fixture",
    coverage: 7,
    period: 16,
    date: 1774972800,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/san-marino-vs-andorra/327w577byq8okh8gsns0fb0gk",
    home: {
      id: "1k3d99pxzs3s2p6ls5somgddd",
      name: "San Marino",
    },
    away: {
      id: "15cc7j7vgomftuc4fn861w3rr",
      name: "Andorra",
    },
    updated: 1774651703,
  },
  {
    id: "cca8rjahua6mw1d35urjurggk",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774972800,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/serbia-vs-saudi-arabia/cca8rjahua6mw1d35urjurggk",
    home: {
      id: "2ome9qbio8c3r9lmhx2hg6kif",
      name: "Serbia",
    },
    away: {
      id: "9l4imoomrnyceg5u3kdxf5l5r",
      name: "Saudi Arabia",
    },
    updated: 1774638454,
  },
  {
    id: "50p8lu6fbsjub91zghr5mrt3o",
    status: "fixture",
    coverage: 9,
    period: 16,
    date: 1774972800,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/zimbabwe-vs-zambia/50p8lu6fbsjub91zghr5mrt3o",
    home: {
      id: "clai5b8pxjwlxl6prcg403owt",
      name: "Zimbabwe",
    },
    away: {
      id: "ajr8xan41mcpd0icx6o0fua12",
      name: "Zambia",
    },
    updated: 1774855706,
  },
  {
    id: "b88ffsfyj3z39sglh5583bims",
    status: "fixture",
    coverage: 9,
    period: 16,
    date: 1774974600,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/haiti-vs-iceland/b88ffsfyj3z39sglh5583bims",
    home: {
      id: "151psmk1h1c846f2lqmflkx75",
      name: "Haiti",
    },
    away: {
      id: "5gv6rrm6m6ixf8nff08vx7i9m",
      name: "Iceland",
    },
    updated: 1774715950,
  },
  {
    id: "ex692d8oe3meocwng8h05rhg4",
    status: "fixture",
    coverage: 15,
    period: 16,
    date: 1774976400,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/hungary-vs-greece/ex692d8oe3meocwng8h05rhg4",
    home: {
      id: "ajqq56th1sg5f7kcx9yon9z6x",
      name: "Hungary",
    },
    away: {
      id: "9rno14cqmifl7hxuxmsnd8j87",
      name: "Greece",
    },
    updated: 1774429561,
  },
  {
    id: "78q8hsg36uk478w34agnfieqc",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774976400,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/russia-vs-mali/78q8hsg36uk478w34agnfieqc",
    home: {
      id: "f0frccyrlq2jjihdraoie2e2d",
      name: "Russia",
    },
    away: {
      id: "cxyx46bv9vb34u58vu4hkc26q",
      name: "Mali",
    },
    updated: 1774709520,
  },
  {
    id: "33e3v1supdgbr51z49zfwkidw",
    status: "fixture",
    coverage: 9,
    period: 16,
    date: 1774978200,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/jordan-vs-nigeria/33e3v1supdgbr51z49zfwkidw",
    home: {
      id: "btn8ibf55ovz7y252vdiprbip",
      name: "Jordan",
    },
    away: {
      id: "ao3zo8i0kn3grl47nol24gck0",
      name: "Nigeria",
    },
    updated: 1774615610,
  },
  {
    id: "ec0sbf7yknz58qdojafa0rztg",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774978200,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/south-africa-vs-panama/ec0sbf7yknz58qdojafa0rztg",
    home: {
      id: "xmip8t9f2kefltjkraxzsxl9",
      name: "South Africa",
    },
    away: {
      id: "8856r86rattc8kxn6a0l9tb2t",
      name: "Panama",
    },
    updated: 1773838333,
  },
  {
    id: "9ihf13ug104tb9t8pjaivd5w4",
    status: "fixture",
    coverage: 1,
    period: 16,
    date: 1774980000,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/guinea-vs-benin/9ihf13ug104tb9t8pjaivd5w4",
    home: {
      id: "78usrkl6yfz4wvawmrp4pqshg",
      name: "Guinea",
    },
    away: {
      id: "3ncpapaqhtddxaoqhy1hbptnx",
      name: "Benin",
    },
    updated: 1774373771,
  },
  {
    id: "77hzffnp3jua5x9isndy8g0es",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774980000,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/morocco-vs-paraguay/77hzffnp3jua5x9isndy8g0es",
    home: {
      id: "avggs3u2b5cu8i1dnzknhth52",
      name: "Morocco",
    },
    away: {
      id: "3cwjdmekfdouwg990mqdq9fh0",
      name: "Paraguay",
    },
    updated: 1774745353,
  },
  {
    id: "45lsqjvbhabx9atmv27q5mivo",
    status: "fixture",
    coverage: 1,
    period: 16,
    date: 1774980000,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/niger-vs-togo/45lsqjvbhabx9atmv27q5mivo",
    home: {
      id: "arnw7kg5oi1k6nzyydcgb88um",
      name: "Niger",
    },
    away: {
      id: "36ultk6i435t1ih018cxzeqtr",
      name: "Togo",
    },
    updated: 1774435725,
  },
  {
    id: "wh7yya34s2j2fa0efl80hogk",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774980000,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/peru-vs-honduras/wh7yya34s2j2fa0efl80hogk",
    home: {
      id: "a9sendamrqqz1uv4jc89mfum8",
      name: "Peru",
    },
    away: {
      id: "6ngz19ekzqqufux1sswnhzlsw",
      name: "Honduras",
    },
    updated: 1774771165,
  },
  {
    id: "f4l46w4b6zt9uacoocwttnthw",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774981800,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/algeria-vs-uruguay/f4l46w4b6zt9uacoocwttnthw",
    home: {
      id: "cbx8lz7loz866tsoawwrpxyl9",
      name: "Algeria",
    },
    away: {
      id: "9l06impjllgop0gte8fldb4zo",
      name: "Uruguay",
    },
    updated: 1774353899,
  },
  {
    id: "1bqsuzt93hkhhk7o8z88oppn8",
    status: "fixture",
    coverage: 15,
    period: 16,
    date: 1774981800,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/côte-d-ivoire-vs-scotland/1bqsuzt93hkhhk7o8z88oppn8",
    home: {
      id: "39d8zamp9tvg3wc51jxc2a1c0",
      name: "Côte d'Ivoire",
    },
    away: {
      id: "bcllqlzvj9j7opjene2zvran7",
      name: "Scotland",
    },
    updated: 1774878139,
  },
  {
    id: "ccw6dk24x09z8yuyolnas5puc",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774982700,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/austria-vs-korea-republic/ccw6dk24x09z8yuyolnas5puc",
    home: {
      id: "61g4epojd5f198lv1sje27yh3",
      name: "Austria",
    },
    away: {
      id: "1yghbv1c71b37eenutbwnvvq",
      name: "Korea Republic",
    },
    updated: 1773766359,
  },
  {
    id: "7dvu9pni7lpkg85ruh97uq51w",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774982700,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/england-vs-japan/7dvu9pni7lpkg85ruh97uq51w",
    home: {
      id: "ck8m1cn23sukwsurgx5qakttk",
      name: "England",
    },
    away: {
      id: "6duaxcbrofil112qfq4v895go",
      name: "Japan",
    },
    updated: 1774548427,
  },
  {
    id: "1ph4zox9cr5l78sog1srcfcpg",
    status: "fixture",
    coverage: 15,
    period: 16,
    date: 1774982700,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/netherlands-vs-ecuador/1ph4zox9cr5l78sog1srcfcpg",
    home: {
      id: "657oha8nkne1ybba2bouzkbo7",
      name: "Netherlands",
    },
    away: {
      id: "2j2402oabiovxw24cnjk9m369",
      name: "Ecuador",
    },
    updated: 1774712377,
  },
  {
    id: "d637metlehun4vy9sen5t4ro4",
    status: "fixture",
    coverage: 15,
    period: 16,
    date: 1774982700,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/republic-of-ireland-vs-north-macedonia/d637metlehun4vy9sen5t4ro4",
    home: {
      id: "eci7cwjcf0q2q61apwsag0vac",
      name: "Republic of Ireland",
    },
    away: {
      id: "4u2lrl06blm7j4r3udbkb5wx9",
      name: "North Macedonia",
    },
    updated: 1774868029,
  },
  {
    id: "d83ccid36jge7cftly5y3pp1w",
    status: "fixture",
    coverage: 9,
    period: 16,
    date: 1774982700,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/slovakia-vs-romania/d83ccid36jge7cftly5y3pp1w",
    home: {
      id: "7ntk6fzpvcrgl55evfr1z7xmv",
      name: "Slovakia",
    },
    away: {
      id: "1qiyr1mknujsl19tb9u2w9h3n",
      name: "Romania",
    },
    updated: 1774609354,
  },
  {
    id: "64am258pzfb02irhakhcuv4es",
    status: "fixture",
    coverage: 9,
    period: 16,
    date: 1774982700,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/ukraine-vs-albania/64am258pzfb02irhakhcuv4es",
    home: {
      id: "7a8no9dyo0r9g31sfi9h7ffbc",
      name: "Ukraine",
    },
    away: {
      id: "e16t9nbq9z9bm2npalbr0me0a",
      name: "Albania",
    },
    updated: 1774771165,
  },
  {
    id: "9bxwmhx4dqtrwxdygzl3h9yxg",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774982700,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/wales-vs-northern-ireland/9bxwmhx4dqtrwxdygzl3h9yxg",
    home: {
      id: "eyhp0bgsz2deg91xaw4zotn5c",
      name: "Wales",
    },
    away: {
      id: "awn64nh0odux22yj90jcxwklg",
      name: "Northern Ireland",
    },
    updated: 1774868046,
  },
  {
    id: "dkpuc8g5je1ioa53r0agmuzo4",
    status: "fixture",
    coverage: 1,
    period: 16,
    date: 1774983600,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/burkina-faso-vs-guinea-bissau/dkpuc8g5je1ioa53r0agmuzo4",
    home: {
      id: "etmdes5ggjhtxte8v8ceiwbio",
      name: "Burkina Faso",
    },
    away: {
      id: "89yydoz414paf1d9r8sgita0t",
      name: "Guinea-Bissau",
    },
    updated: 1774363887,
  },
  {
    id: "1hphw2zgwei5xupf3am36lct0",
    status: "fixture",
    coverage: 9,
    period: 16,
    date: 1774983600,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/senegal-vs-gambia/1hphw2zgwei5xupf3am36lct0",
    home: {
      id: "2wk1549tkz80oet8226euj7jp",
      name: "Senegal",
    },
    away: {
      id: "6w9lenap2haqufnz7ptcr3x2t",
      name: "Gambia",
    },
    updated: 1774719947,
  },
  {
    id: "52cm9g2ph41wy7jcvhjsbkc9g",
    status: "fixture",
    coverage: 13,
    period: 16,
    date: 1774983600,
    comp: {
      id: "cesdwwnxbc5fmajgroc0hqzy2",
      name: "Friendlies",
      nameSeo: "friendlies",
      country: {
        id: "7yasa43laq1nb2e6f8bfuvxed",
        name: "world",
        fullName: "World",
        nameSeo: "world",
        flag: "/images/flags/fifa.png",
      },
      link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/results",
    },
    link: "/en_GB/soccer/friendlies-2026/dezv8l0fzgcxtejl0dwmy1gyc/match/spain-vs-egypt/52cm9g2ph41wy7jcvhjsbkc9g",
    home: {
      id: "eh7yt2x2wck51oixw8012ux5j",
      name: "Spain",
    },
    away: {
      id: "3669sbeijslw88073qlw1cbcp",
      name: "Egypt",
    },
    updated: 1774339479,
  },
];
