/**
 * أندية مغربية — ترتيب تجريبي في البطولة الاحترافية.
 */

export const MOROCCAN_CLUBS = [
  {
    slug: "wydad",
    name: "الوداد الرياضي",
    shortName: "الوداد",
    city: "الدار البيضاء",
    logo: "/clubs/wydad.svg",
    colors: "#E3212D",
    ranking: {
      leagueRank: 1,
      points: 47,
      played: 22,
      won: 14,
      draw: 5,
      lost: 3,
      goalsFor: 38,
      goalsAgainst: 20,
    },
  },
  {
    slug: "raja",
    name: "الرجاء الرياضي",
    shortName: "الرجاء",
    city: "الدار البيضاء",
    logo: "/clubs/raja.svg",
    colors: "#00954A",
    ranking: {
      leagueRank: 2,
      points: 45,
      played: 22,
      won: 13,
      draw: 6,
      lost: 3,
      goalsFor: 35,
      goalsAgainst: 18,
    },
  },
  {
    slug: "berkane",
    name: "نهضة بركان",
    shortName: "بركان",
    city: "بركان",
    logo: "/clubs/berkane.svg",
    colors: "#F47C20",
    ranking: {
      leagueRank: 3,
      points: 42,
      played: 22,
      won: 12,
      draw: 6,
      lost: 4,
      goalsFor: 31,
      goalsAgainst: 22,
    },
  },
  {
    slug: "fes",
    name: "المغرب الفاسي",
    shortName: "المغرب الفاسي",
    city: "فاس",
    logo: "/clubs/fes.svg",
    colors: "#1B5E20",
    ranking: {
      leagueRank: 4,
      points: 38,
      played: 22,
      won: 10,
      draw: 8,
      lost: 4,
      goalsFor: 28,
      goalsAgainst: 24,
    },
  },
  {
    slug: "as-far",
    name: "الجيش الملكي",
    shortName: "الجيش الملكي",
    city: "الرباط",
    logo: "/clubs/asfar.svg",
    colors: "#C62828",
    ranking: {
      leagueRank: 5,
      points: 36,
      played: 22,
      won: 9,
      draw: 9,
      lost: 4,
      goalsFor: 26,
      goalsAgainst: 22,
    },
  },
  {
    slug: "mohammedia",
    name: "شباب المحمدية",
    shortName: "المحمدية",
    city: "المحمدية",
    logo: "/clubs/mohammedia.svg",
    colors: "#1565C0",
    ranking: {
      leagueRank: 6,
      points: 34,
      played: 22,
      won: 9,
      draw: 7,
      lost: 6,
      goalsFor: 24,
      goalsAgainst: 25,
    },
  },
  {
    slug: "wydad",
    name: "الوداد الرياضي",
    shortName: "الوداد",
    city: "الدار البيضاء",
    logo: "/clubs/wydad.svg",
    colors: "#E3212D",
    ranking: {
      leagueRank: 1,
      points: 47,
      played: 22,
      won: 14,
      draw: 5,
      lost: 3,
      goalsFor: 38,
      goalsAgainst: 20,
    },
  },
  {
    slug: "raja",
    name: "الرجاء الرياضي",
    shortName: "الرجاء",
    city: "الدار البيضاء",
    logo: "/clubs/raja.svg",
    colors: "#00954A",
    ranking: {
      leagueRank: 2,
      points: 45,
      played: 22,
      won: 13,
      draw: 6,
      lost: 3,
      goalsFor: 35,
      goalsAgainst: 18,
    },
  },
  {
    slug: "berkane",
    name: "نهضة بركان",
    shortName: "بركان",
    city: "بركان",
    logo: "/clubs/berkane.svg",
    colors: "#F47C20",
    ranking: {
      leagueRank: 3,
      points: 42,
      played: 22,
      won: 12,
      draw: 6,
      lost: 4,
      goalsFor: 31,
      goalsAgainst: 22,
    },
  },
  {
    slug: "fes",
    name: "المغرب الفاسي",
    shortName: "المغرب الفاسي",
    city: "فاس",
    logo: "/clubs/fes.svg",
    colors: "#1B5E20",
    ranking: {
      leagueRank: 4,
      points: 38,
      played: 22,
      won: 10,
      draw: 8,
      lost: 4,
      goalsFor: 28,
      goalsAgainst: 24,
    },
  },
  {
    slug: "as-far",
    name: "الجيش الملكي",
    shortName: "الجيش الملكي",
    city: "الرباط",
    logo: "/clubs/asfar.svg",
    colors: "#C62828",
    ranking: {
      leagueRank: 5,
      points: 36,
      played: 22,
      won: 9,
      draw: 9,
      lost: 4,
      goalsFor: 26,
      goalsAgainst: 22,
    },
  },
  {
    slug: "mohammedia",
    name: "شباب المحمدية",
    shortName: "المحمدية",
    city: "المحمدية",
    logo: "/clubs/mohammedia.svg",
    colors: "#1565C0",
    ranking: {
      leagueRank: 6,
      points: 34,
      played: 22,
      won: 9,
      draw: 7,
      lost: 6,
      goalsFor: 24,
      goalsAgainst: 25,
    },
  },
  {
    slug: "wydad",
    name: "الوداد الرياضي",
    shortName: "الوداد",
    city: "الدار البيضاء",
    logo: "/clubs/wydad.svg",
    colors: "#E3212D",
    ranking: {
      leagueRank: 1,
      points: 47,
      played: 22,
      won: 14,
      draw: 5,
      lost: 3,
      goalsFor: 38,
      goalsAgainst: 20,
    },
  },
  {
    slug: "raja",
    name: "الرجاء الرياضي",
    shortName: "الرجاء",
    city: "الدار البيضاء",
    logo: "/clubs/raja.svg",
    colors: "#00954A",
    ranking: {
      leagueRank: 2,
      points: 45,
      played: 22,
      won: 13,
      draw: 6,
      lost: 3,
      goalsFor: 35,
      goalsAgainst: 18,
    },
  },
  {
    slug: "berkane",
    name: "نهضة بركان",
    shortName: "بركان",
    city: "بركان",
    logo: "/clubs/berkane.svg",
    colors: "#F47C20",
    ranking: {
      leagueRank: 3,
      points: 42,
      played: 22,
      won: 12,
      draw: 6,
      lost: 4,
      goalsFor: 31,
      goalsAgainst: 22,
    },
  },
  {
    slug: "fes",
    name: "المغرب الفاسي",
    shortName: "المغرب الفاسي",
    city: "فاس",
    logo: "/clubs/fes.svg",
    colors: "#1B5E20",
    ranking: {
      leagueRank: 4,
      points: 38,
      played: 22,
      won: 10,
      draw: 8,
      lost: 4,
      goalsFor: 28,
      goalsAgainst: 24,
    },
  },
];

export function getClubBySlug(slug) {
  return MOROCCAN_CLUBS.find((c) => c.slug === slug) ?? null;
}

export function getAllClubSlugs() {
  return MOROCCAN_CLUBS.map((c) => c.slug);
}
